config/routes.rb
Dicom::Application.routes.draw do
  get "search/index"
  get "search/getZip"
  resources :examinations

  root 'examinations#index'

end

app/models/dicom_images.rb
class DicomImages < ActiveRecord::Base
  self.table_name = 'DICOMImages'
  belongs_to :dicom_series
end

app/models/dicom_patients.rb
class DicomPatients < ActiveRecord::Base
  self.table_name = 'DICOMPatients'
end

app/models/dicom_series.rb
class DicomSeries < ActiveRecord::Base
  self.table_name = 'DICOMSeries'
  has_many :dicom_images
end

app/models/dicom_studies.rb
class DicomStudies < ActiveRecord::Base
  self.table_name = 'DICOMStudies'
end

app/models/dicom_work_list.rb
class DicomWorkList < ActiveRecord::Base
  self.table_name = 'DICOMWorkList'
end

app/models/examination.rb
class Examination < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/examinations_controller.rb
class ExaminationsController < ApplicationController
  before_action :set_examination, only: [:show, :edit, :update, :destroy]

  # GET /examinations
  # GET /examinations.json
  # def index
  #   @examinations = Examination.all
  # end

  def index
    @examinations = Examination.find(:all)

    @study = params[:study]
    @mean_exposure = Examination.average(:exposure, :conditions => ['study == ?', @study]) if @study

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @examinations }
    end
  end
  # GET /examinations/1
  # GET /examinations/1.json
  def show
  end

  # GET /examinations/new
  def new
    @examination = Examination.new
  end

  # GET /examinations/1/edit
  def edit
  end

  # POST /examinations
  # POST /examinations.json
  def create
    @examination = Examination.new(examination_params)

    respond_to do |format|
      if @examination.save
        format.html { redirect_to @examination, notice: 'Examination was successfully created.' }
        format.json { render action: 'show', status: :created, location: @examination }
      else
        format.html { render action: 'new' }
        format.json { render json: @examination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examinations/1
  # PATCH/PUT /examinations/1.json
  def update
    respond_to do |format|
      if @examination.update(examination_params)
        format.html { redirect_to @examination, notice: 'Examination was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @examination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examinations/1
  # DELETE /examinations/1.json
  def destroy
    @examination.destroy
    respond_to do |format|
      format.html { redirect_to examinations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_examination
      @examination = Examination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def examination_params
      params.require(:examination).permit(:study, :name, :voltage, :current, :exposure)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    type = params[:type]

    if type == "name"
      # @examination = Dicom.select(type).uniq
    elsif type == "series"
      type = "SeriesDesc"
      @dicom_series = DicomSeries.select(type).uniq
    else
      @dicom_series = DicomSeries.all
    end

    respond_to do |format|
      format.json { render :json => @dicom_series, callback: params[:callback] }
    end
  end

  def getZip
    series = params[:series]

    # dicom_series = DicomSeries.where("SeriesDesc = ?",series).select("SeriesInst")

    dicom_series = DicomImages.joins("LEFT OUTER JOIN `DICOMSeries` ON `DICOMSeries`.`SeriesInst` = `DICOMImages`.`SeriesInst`").where("`DICOMSeries`.`SeriesDesc` = ?", series).select("`DICOMImages`.`ObjectFile`")

    #logger.debug (examination.inspect)

    files = ""
    dicom_series.each do |obj|
      files += " " + "/usr/lib/cgi-bin/data/" + obj.ObjectFile
    end

    #logger.debug files.inspect

    zip_folder = Rails.root.join("dicomdir").to_s + "/"

    create_zip_path = zip_folder + series + ".zip"

    command = "zip -j "+ create_zip_path +files

    # logger.debug create_zip_path
    # logger.debug command

    `#{command}`

    stat = File::stat(create_zip_path)

    response.headers['Access-Control-Allow-Origin'] = '*'

    send_file(create_zip_path, :filename => series+'.zip', :length => stat.size)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examinations_helper.rb
module ExaminationsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/examinations/_form.html.erb
<%= form_for(@examination) do |f| %>
  <% if @examination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@examination.errors.count, "error") %> prohibited this examination from being saved:</h2>

      <ul>
      <% @examination.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :study %><br>
    <%= f.text_field :study %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :voltage %><br>
    <%= f.text_field :voltage %>
  </div>
  <div class="field">
    <%= f.label :current %><br>
    <%= f.text_field :current %>
  </div>
  <div class="field">
    <%= f.label :exposure %><br>
    <%= f.text_field :exposure %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/examinations/edit.html.erb
<h1>Editing examination</h1>

<%= render 'form' %>

<%= link_to 'Show', @examination %> |
<%= link_to 'Back', examinations_path %>

app/views/examinations/index.html.erb
<h1>Listing examinations</h1>

<table>
  <tr>
    <th>Study</th>
    <th>Name</th>
    <th>Voltage</th>
    <th>Current</th>
    <th>Exposure</th>
  </tr>

  <% @examinations.each do |examination| %>
  <% unless @study and @study != examination.study %>
  <tr>
    <td><%= link_to examination.study, :action => 'index', :study => examination.study %></td>
    <td><%= examination.name %></td>
    <td><%= examination.voltage %></td>
    <td><%= examination.current %></td>
    <td><%= examination.exposure %></td>
    <td><%= link_to 'Show', examination %></td>
    <td><%= link_to 'Edit', edit_examination_path(examination) %></td>
    <td><%= link_to 'Destroy', examination, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
  <% end %>
  <% end %>
</table>

<% if @mean_exposure %>
<br /><%= "Mean exposure: #{@mean_exposure}" %><br />
<% end %>
<br />
<%= link_to 'Show all', examinations_path %>

app/views/examinations/new.html.erb
<h1>New examination</h1>

<%= render 'form' %>

<%= link_to 'Back', examinations_path %>

app/views/examinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Study:</strong>
  <%= @examination.study %>
</p>

<p>
  <strong>Name:</strong>
  <%= @examination.name %>
</p>

<p>
  <strong>Voltage:</strong>
  <%= @examination.voltage %>
</p>

<p>
  <strong>Current:</strong>
  <%= @examination.current %>
</p>

<p>
  <strong>Exposure:</strong>
  <%= @examination.exposure %>
</p>

<%= link_to 'Edit', edit_examination_path(@examination) %> |
<%= link_to 'Back', examinations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dicom</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/index.html.erb
<h1>Search#index</h1>
<p>Find me in app/views/search/index.html.erb</p>